import open3d as o3d
import numpy as np
import copy
import glob
import os
import sys

# ==========================================
# 0. GET TARGET FOLDER FROM COMMAND LINE
# ==========================================
if len(sys.argv) > 1:
    target_folder = sys.argv[1]
    if not os.path.isdir(target_folder):
        print(f"Error: Folder '{target_folder}' does not exist.")
        sys.exit(1)
else:
    target_folder = "."   # fallback to current directory
    print("No folder specified, using current directory.")

print(f"Scanning for point clouds in: {os.path.abspath(target_folder)}")

# ==========================================
# 1. ROBUST FILE LOADING
# ==========================================
def load_custom_xyz(filepath):
    """
    Parses .Rxyz or .xyz files generated by save2.py.
    Handles headers, comments, and intensity columns.
    """
    print(f" -> Loading {os.path.basename(filepath)}...")
    pts = []
    intensities = []
    
    try:
        with open(filepath, 'r') as f:
            for line in f:
                # Skip comments
                if line.startswith("#"): 
                    continue
                
                parts = line.split()
                # Ensure we have at least X, Y, Z
                if len(parts) >= 3:
                    try:
                        pts.append([float(parts[0]), float(parts[1]), float(parts[2])])
                        # Optional: Capture intensity if available (for visualization later)
                        if len(parts) >= 4:
                            intensities.append(float(parts[3]))
                    except ValueError:
                        continue
    except Exception as e:
        print(f"Error reading file: {e}")
        return None

    if not pts:
        print(f"Warning: {filepath} contains no valid points.")
        return None

    # Create Open3D PointCloud
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(np.array(pts))
    
    # Pre-processing: Downsample & Estimate Normals (CRITICAL for ICP)
    # Voxel size 0.03 = 3cm resolution. Adjust if your room is huge.
    pcd_down = pcd.voxel_down_sample(voxel_size=0.03)
    pcd_down.estimate_normals(
        search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30)
    )
    
    # Paint it a uniform color (Grey) to start, so we can distinguish source/target later
    pcd_down.paint_uniform_color([0.6, 0.6, 0.6])
    
    return pcd_down

# ==========================================
# 2. INTERACTIVE POINT PICKING
# ==========================================
def pick_points(pcd, window_name):
    """
    Opens a window for the user to pick points.
    Returns the INDICES of picked points.
    """
    print(f"\n--- {window_name} ---")
    print("   1) Hold [Shift + Left Click] to pick a point.")
    print("   2) Select at least 3 points (corners, distinct objects).")
    print("   3) Press [Q] to close the window and confirm.")
    
    vis = o3d.visualization.VisualizerWithEditing()
    vis.create_window(window_name=window_name, width=960, height=720)
    vis.add_geometry(pcd)
    
    # Blocks execution until user closes window
    vis.run() 
    vis.destroy_window()
    
    # Return the indices of the points the user clicked
    return vis.get_picked_points()

# ==========================================
# 3. REGISTRATION LOGIC
# ==========================================
def manual_registration(source, target):
    """
    Aligns 'source' to 'target' using user-selected correspondences.
    """
    # Create copies to avoid messing up originals during visualization
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    
    # Color them differently for the user
    source_temp.paint_uniform_color([1, 0.706, 0])      # Yellow (Source)
    target_temp.paint_uniform_color([0, 0.651, 0.929])  # Blue (Target)

    # --- Step A: Pick Points on Target (Base) ---
    print("\n[USER ACTION REQUIRED]")
    print("Pick 3 corresponding points on the BLUE cloud (The Map so far).")
    picked_id_target = pick_points(target_temp, "Pick 3 Points on TARGET (Blue)")
    
    if len(picked_id_target) < 3:
        print("Error: You picked fewer than 3 points. Skipping this scan.")
        return np.identity(4)

    # --- Step B: Pick Points on Source (New Scan) ---
    print("\n[USER ACTION REQUIRED]")
    print("Pick the SAME 3 points on the YELLOW cloud (The New Scan).")
    picked_id_source = pick_points(source_temp, "Pick 3 Points on SOURCE (Yellow)")

    if len(picked_id_source) < 3:
        print("Error: You picked fewer than 3 points. Skipping this scan.")
        return np.identity(4)
    
    if len(picked_id_source) != len(picked_id_target):
        print(f"Error: Point count mismatch ({len(picked_id_source)} vs {len(picked_id_target)}). Using first {min(len(picked_id_source), len(picked_id_target))} points.")
        min_len = min(len(picked_id_source), len(picked_id_target))
        picked_id_source = picked_id_source[:min_len]
        picked_id_target = picked_id_target[:min_len]

    # --- Step C: Compute Rough Alignment (Point-to-Point) ---
    print(" -> Computing rough alignment...")
    corr = np.zeros((len(picked_id_source), 2))
    corr[:, 0] = picked_id_source
    corr[:, 1] = picked_id_target

    # Estimate transformation using the picked pairs
    p2p_estimator = o3d.pipelines.registration.TransformationEstimationPointToPoint()
    trans_init = p2p_estimator.compute_transformation(source_temp, target_temp, o3d.utility.Vector2iVector(corr))

    # --- Step D: Refine Alignment (Point-to-Plane ICP) ---
    # This snaps the clouds tightly together using local geometry
    print(" -> Refining with ICP (Point-to-Plane)...")
    threshold = 0.05  # 5cm max distance for snapping
    
    reg_p2l = o3d.pipelines.registration.registration_icp(
        source, target, threshold, trans_init,
        o3d.pipelines.registration.TransformationEstimationPointToPlane()
    )
    
    print(f" -> Alignment Fitness: {reg_p2l.fitness:.4f} (Higher is better)")
    print(f" -> RMSE: {reg_p2l.inlier_rmse:.4f} (Lower is better)")
    
    return reg_p2l.transformation

# ==========================================
# 4. MAIN LOOP
# ==========================================
def main():
    # Find files only inside the specified folder
    search_pattern_rxyz = os.path.join(target_folder, "*.Rxyz")
    search_pattern_xyz  = os.path.join(target_folder, "*.xyz")
    files = sorted(glob.glob(search_pattern_rxyz) + glob.glob(search_pattern_xyz))
    
    if len(files) < 2:
        print(f"Error: Need at least 2 .Rxyz or .xyz files in folder '{target_folder}'.")
        sys.exit(1)

    print("=========================================")
    print(f"Found {len(files)} scans to merge.")
    print("Instruction: Pick corresponding points to stitch scans together.")
    print("=========================================")

    # Load first file as global map
    global_pcd = load_custom_xyz(files[0])
    if global_pcd is None:
        sys.exit(1)

    # Iteratively add the rest
    for i in range(1, len(files)):
        filename = files[i]
        print(f"\nProcessing {i+1}/{len(files)}: {os.path.basename(filename)}")
        
        # Load new scan
        new_pcd = load_custom_xyz(filename)
        if new_pcd is None: continue

        # Perform Manual Registration
        transform_matrix = manual_registration(new_pcd, global_pcd)
        
        # Apply transformation to the new scan
        new_pcd.transform(transform_matrix)
        
        # Merge into global map
        global_pcd += new_pcd
        
        # Clean up global map (remove duplicates/overlap to keep it fast)
        global_pcd = global_pcd.voxel_down_sample(voxel_size=0.03)

    # --- Final Visualization ---
    print("\nProcessing Complete!")
    print("Visualizing Final Merged Cloud...")
    
    # Recalculate normals for nice lighting
    global_pcd.estimate_normals()
    
    o3d.visualization.draw_geometries([global_pcd], 
                                      window_name="Final Merged Map",
                                      width=1024, height=768)

    # Save (place the output in the same folder as the scans)
    save_name = os.path.join(target_folder, "Final_Merged_Room.xyz")
    o3d.io.write_point_cloud(save_name, global_pcd)
    print(f"Saved merged cloud to: {save_name}")

if __name__ == "__main__":
    main()